export const USER_MANAGEMENT_ACTIONS = {
  GET_USER: 'USER_MANAGEMENT_ACTIONS.GET_USER',
  GET_TOTAL_COUNT_USER: 'USER_MANAGEMENT_ACTIONS.GET_TOTAL_COUNT_USER',
  SET_IS_USER_DATA_LOADING: 'USER_MANAGEMENT_ACTIONS.SET_IS_USER_DATA_LOADING',
  SET_FILTERS: 'USER_MANAGEMENT_ACTIONS.SET_FILTERS',
};
